"""
Django settings for home project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ei9ky@^x@eo-w-ok**0sblu6$!j!y=(*77ol7*q&ib_fbzveq1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver', 'pet-walfare.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'webapp',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'home.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                    'webapp.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'home.wsgi.application'


# Database - Dynamic Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Base database configuration: rely solely on DATABASE_URL in deployed environments.
DATABASES = {}

# Prefer DATABASE_URL (set on Render) for the default connection when available.
database_url = os.environ.get('DATABASE_URL')
if database_url:
    db_cfg = dj_database_url.config(
        default=database_url,
        conn_max_age=600,
        ssl_require=True,
    )

    # Clean unsupported sslmode/ssl-mode and rely on driver-supported ssl dict.
    opts = db_cfg.get('OPTIONS', {})
    opts.pop('sslmode', None)
    opts.pop('ssl-mode', None)
    opts.setdefault('ssl', {})  # mysqlclient accepts a dict here; empty uses system CA
    db_cfg['OPTIONS'] = opts

    DATABASES['default'] = db_cfg

# Ensure a default DB exists; if not configured, raise clearly to avoid silent sqlite fallback.
if 'default' not in DATABASES:
    raise RuntimeError('DATABASE_URL is required for database configuration')

# Separate chat database (Aiven chat_database)
chat_db_url = os.environ.get('CHAT_DATABASE_URL')
if chat_db_url:
    chat_cfg = dj_database_url.config(
        default=chat_db_url,
        conn_max_age=600,
        ssl_require=True,
    )
    # Clean unsupported sslmode/ssl-mode
    chat_opts = chat_cfg.get('OPTIONS', {})
    chat_opts.pop('sslmode', None)
    chat_opts.pop('ssl-mode', None)
    chat_opts.setdefault('ssl', {})
    chat_cfg['OPTIONS'] = chat_opts
    DATABASES['chat_db'] = chat_cfg
else:
    # Fallback to using the default database for chat if CHAT_DATABASE_URL not set
    DATABASES['chat_db'] = DATABASES['default'].copy()

# Route chat app models to chat_db
DATABASE_ROUTERS = ['chat.db_routers.ChatRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cloudinary Configuration
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', 'dupeyfqh8'),
    api_key=os.environ.get('CLOUDINARY_API_KEY', '191396433295353'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', 'ahFrKF2kFFwv9jDQTHLYuItUPUI'),
    secure=True
)

# Media files via Cloudinary
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication Settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'